/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Labyrinth;

import javax.swing.*;

import static javax.swing.ListSelectionModel.SINGLE_SELECTION;

/**
 *
 * @author Remi
 */
public class WallForm extends javax.swing.JFrame {
    
    // object to connect with database
    private MyConnection myConnection;
    
    // constructor
    public WallForm() {        
        initComponents();

        try {
            /* this code create new variable using class Connection
             * the code inside the class constructor will connect with database
             * execute the sql query, counts rows and columns of data
             * create table model.
             * The size of table (rows and columns) depends from data set that
             * sql query return. It means that table is resizeable dynamically.
             */
            myConnection = new MyConnection("SELECT level,points,nick FROM bestscore WHERE (level, points) IN (SELECT level, MAX( points ) FROM bestscore GROUP BY level) ORDER BY  `level`;");
            // player can select only one row
            tblBestScores.setSelectionMode(SINGLE_SELECTION);
            // set model to application table
            tblBestScores.setModel(myConnection.getTableModel());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Can't fill up tha table with score data.", "Communications link failure", 0);
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        btnExit = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        spTableCointainer = new javax.swing.JScrollPane();
        tblBestScores = new javax.swing.JTable();
        lblRulesImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 650));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(255, 255, 204));
        panel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnExit.setText("Exit");
        btnExit.setName(""); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("The Best Results");

        spTableCointainer.setViewportView(tblBestScores);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap(629, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(113, Short.MAX_VALUE)
                    .addComponent(spTableCointainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(125, Short.MAX_VALUE)))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(spTableCointainer, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        getContentPane().add(panel1);
        panel1.setBounds(30, 150, 690, 470);

        lblRulesImage.setIcon(new ImageIcon(getClass().getResource("/MyLabResources/loginImage750x650.jpg"))); // NOI18N
        lblRulesImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblRulesImage.setMaximumSize(new java.awt.Dimension(750, 650));
        lblRulesImage.setMinimumSize(new java.awt.Dimension(750, 650));
        lblRulesImage.setPreferredSize(new java.awt.Dimension(750, 650));
        getContentPane().add(lblRulesImage);
        lblRulesImage.setBounds(0, 0, 750, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WallForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblRulesImage;
    private javax.swing.JLabel lblTitle;
    private java.awt.Panel panel1;
    private javax.swing.JScrollPane spTableCointainer;
    private javax.swing.JTable tblBestScores;
    // End of variables declaration//GEN-END:variables
}
